# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-15 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=50)),
                ('text', models.FileField(upload_to='')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('confırm_types', models.PositiveSmallIntegerField(choices=[(0, 'CONFIRM'), (1, 'EDIT'), (2, 'WAITING')], default=2, verbose_name='CONFIRM_TYPE')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazine_name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Magazine',
                'verbose_name_plural': 'Magazines',
            },
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Number')),
            ],
            options={
                'verbose_name': 'Number',
                'verbose_name_plural': 'Numbers',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publishers',
            },
        ),
        migrations.AddField(
            model_name='magazine',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazines.Number', verbose_name='Number'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='publisher',
            field=models.ManyToManyField(to='magazines.Publisher', verbose_name='Publisher'),
        ),
        migrations.AddField(
            model_name='article',
            name='number',
            field=models.ManyToManyField(to='magazines.Number', verbose_name='Number'),
        ),
    ]
